name: Deploy IIS Static Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Upload website as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: '/published/**'

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app987654321'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_171DED316BCF4E63AD520388D1E20BC3 }}
          package: .
